Repository SOPT-29th-Joint-Seminar-6/iOS_KakaoTalk, pull requests merged in 2021-11, with the labels that each got.

#3 [FEAT] 커스텀 탭바 추가
  iOS_KakaoTalk/iOS_KakaoTalk.xcodeproj/project.pbxproj
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgKakaoview.imageset/Contents.json
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgKakaoview.imageset/imgKakaoview.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgKakaoview.imageset/imgKakaoview@2x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgKakaoview.imageset/imgKakaoview@3x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/CustomTabbarTitles.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/BaseTabBar.storyboard
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/CustomTabbar.xib
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/CustomTabbarCell.xib
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/Discovery.storyboard
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/KakaoTV.storyboard
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/View.storyboard
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/Cell/CustomTabbarCell.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/ViewController/DiscoveryVC.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/ViewController/KakaoTVVC.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/ViewController/ViewVC.swift
Labels: inhwan, feat

#8 [#7] color extension 추가
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Extension/UIColor.swift
Labels: inhwan, feat

#5 [#4] 커스텀 탭바 이동시 라벨 밝기 조절 구현
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Extension/UIColor.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/CustomTabbarCell.xib
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/ViewController/ViewVC.swift
Labels: inhwan

#12 [#6] 카카오TV 탭 구현
  iOS_KakaoTalk/iOS_KakaoTalk.xcodeproj/project.pbxproj
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/icAlert.imageset/Contents.json
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/icAlert.imageset/icAlert.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/icAlert.imageset/icAlert@2x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/icAlert.imageset/icAlert@3x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/icFull.imageset/Contents.json
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/icFull.imageset/icFull.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/icFull.imageset/icFull@2x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/icFull.imageset/icFull@3x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgProfile.imageset/Contents.json
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgProfile.imageset/imgProfile.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgProfile.imageset/imgProfile@2x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgProfile.imageset/imgProfile@3x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgThumbnail.imageset/Contents.json
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgThumbnail.imageset/imgThumbnail.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgThumbnail.imageset/imgThumbnail@2x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgThumbnail.imageset/imgThumbnail@3x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/KakaoTV.storyboard
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/KakaoTVTagListTVCell.xib
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/KakaoTVVideoTVCell.xib
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/Cell/KakaoTVTagListTVCell.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/Cell/KakaoTVVideoTVCell.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/ViewController/KakaoTVVC.swift
Labels: inhwan, feat

#13 [#11] 커스텁 팝업 UI
  iOS_KakaoTalk/.DS_Store
  iOS_KakaoTalk/iOS_KakaoTalk.xcodeproj/project.pbxproj
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/btnCancle.imageset/Contents.json
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/btnCancle.imageset/btnCancle.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/btnCancle.imageset/btnCancle@2x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/btnCancle.imageset/btnCancle@3x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/btnChannel.imageset/Contents.json
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/btnChannel.imageset/btnChannel.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/btnChannel.imageset/btnChannel@2x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/btnChannel.imageset/btnChannel@3x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgCamera.imageset/Contents.json
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgCamera.imageset/imgCamera.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgCamera.imageset/imgCamera@2x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Assets.xcassets/imgCamera.imageset/imgCamera@3x.png
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Constants.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Configuration/Storyboards/ChannelPopUp.storyboard
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/Cell/DiscoverySecondTableViewCell.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/Cell/DiscoverySecondTableViewCell.xib
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/Cell/DiscoveryTableViewCell.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/Cell/DiscoveryTableViewCell.xib
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/ViewController/ChannelPopUpVC.swift
  iOS_KakaoTalk/iOS_KakaoTalk/Sources/ViewController/DiscoveryVC.swift
Labels: yijoon, seungchan, feat
